### ISSUE TITLE
pytorch_model.bin指的是什么，下载下来的文件只有.ckpt文件

### ISSUE THREAD

**Issue by FakerYFX** [NLPScott/bert-Chinese-classification-task#16]
pytorch_model.bin指的是什么，下载下来的文件只有.ckpt文件
@NLPScott

**Comment by FakerYFX** [comment]
我用官网的转换工具把tensorflow的模型转换成pytorch.bin,但是在模型加载的时候报错了
![image](https://user-images.githubusercontent.com/19235054/50673638-396ab780-101a-11e9-984d-7f34fa187ff7.png)
@NLPScott

**Comment by metily** [comment]
同问 这个文件怎么下载的啊，export看不太懂

**Comment by flybird101** [comment]
同求

**Comment by badbubble** [comment]
#13

**Comment by wangbq18** [comment]
同求pytorch_model.bin

**Comment by chenxiaoyouyou** [comment]
from pytorch_pretrained_bert import convert_tf_checkpoint_to_pytorch，使用这个将tf的转换为torch的
convert_tf_checkpoint_to_pytorch.convert_tf_checkpoint_to_pytorch('bert-model/chinese_L-12_H-768_A-12/bert_model.ckpt', 'bert-model/bert_config.json', 'bert-model/pytorch_model.bin')

**Comment by gao233333** [comment]
你就不能把转好的pytorch_model.bin传上去吗，官网tf的跑不了，GCS bucket又要绑定信用卡，这个点了我还没下班，哭了555

**Comment by flybird101** [comment]
> 你就不能把转好的pytorch_model.bin传上去吗，官网tf的跑不了，GCS bucket又要绑定信用卡，这个点了我还没下班，哭了555

https://github.com/xieyufei1993/Bert-Pytorch-Chinese-TextClassification 参考此处转换
