### ISSUE TITLE
model.bert.load_state_dict(torch.load(args.init_checkpoint, map_location='cpu'))

### ISSUE THREAD

**Issue by longredzhong** [NLPScott/bert-Chinese-classification-task#18]
model.bert.load_state_dict(torch.load(args.init_checkpoint, map_location='cpu'))
RuntimeError: Error(s) in loading state_dict for BertModel:
        Missing key(s) in state_dict:
有什么解决办法吗？谢谢！

_Originally posted by @wutonghua in https://github.com/NLPScott/bert-Chinese-classification-task/issues/5#issuecomment-448087171_

**Comment by MrRace** [comment]
解决了吗？同样遇到这个问题，不知道怎么解决

**Comment by twyvip** [comment]
遇到同样的问题，同求解决方案

**Comment by mazicwong** [comment]
这是加载模型时出的错误，因为转换成`pytorch_model.bin`用的函数更新了，现在`pytorch-pretrained-bert`中的`convert_tf_checkpoint_to_pytorch.py`有变化，可以用下面第193个release时候的函数来生成`pytorch_model.bin`

地址在这里:
>[pytorch-pretained-bert with 193 commits](https://github.com/huggingface/pytorch-pretrained-BERT/tree/1de35b624b9d7998feb4d518e4f7e8e53abac4e1)

**Comment by AwsomeName** [comment]
> 这是加载模型时出的错误，因为转换成`pytorch_model.bin`用的函数更新了，现在`pytorch-pretrained-bert`中的`convert_tf_checkpoint_to_pytorch.py`有变化，可以用第一个release时候的函数来生成`pytorch_model.bin`
> 
> 地址在这里:
> 
> > [pytorch-pretained-bert with 193 commits](https://github.com/huggingface/pytorch-pretrained-BERT/tree/1de35b624b9d7998feb4d518e4f7e8e53abac4e1)

我一开始就用这个链接中的代码转换的，chinese-base模型，但是还是报这个错了

**Comment by ylf4910** [comment]
你好，想问一下 这个问题解决了吗？ 现在用更新版本的convert_tf_checkpoint_to_pytorch.py 都还是会出现这样的错误，可以怎么解决呢？

**Comment by rubby33** [comment]
> 这是加载模型时出的错误，因为转换成`pytorch_model.bin`用的函数更新了，现在`pytorch-pretrained-bert`中的`convert_tf_checkpoint_to_pytorch.py`有变化，可以用下面第193个release时候的函数来生成`pytorch_model.bin`
> 
> 地址在这里:
> 
> > [pytorch-pretained-bert with 193 commits](https://github.com/huggingface/pytorch-pretrained-BERT/tree/1de35b624b9d7998feb4d518e4f7e8e53abac4e1)

我用193 和最新commit 代码，自己转成pytorch_model.bin，都还是报错，有什么方法吗。谢谢。 @mazicwong

**Comment by wutonghua** [comment]
谢谢您的来信，稍后给您处理！祝安康！
